"""Initial migration - create businesses, branches tables

Revision ID: b3e6d6d71b9d
Revises: 
Create Date: 2026-01-26 17:02:44.002603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e6d6d71b9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_index('idx_business_branches_branch_id', table_name='business_branches')
    op.drop_index('idx_business_branches_business_id', table_name='business_branches')
    op.drop_index('idx_businesses_city', table_name='businesses', postgresql_using='gin')
    op.drop_index('idx_businesses_fulltext', table_name='businesses', postgresql_using='gin')
    op.drop_index('idx_businesses_name', table_name='businesses', postgresql_using='gin')
    op.drop_index('idx_businesses_postcode', table_name='businesses')
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_postcode'), 'businesses', ['postcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_postcode'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.create_index('idx_businesses_postcode', 'businesses', ['postcode'], unique=False)
    op.create_index('idx_businesses_name', 'businesses', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_businesses_fulltext', 'businesses', [sa.text("to_tsvector('german'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(city, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_businesses_city', 'businesses', ['city'], unique=False, postgresql_using='gin')
    op.create_index('idx_business_branches_business_id', 'business_branches', ['business_id'], unique=False)
    op.create_index('idx_business_branches_branch_id', 'business_branches', ['branch_id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
